// This file is generated by icon spritesheet generator

export const iconNames = [
  "debt",
  "database",
  "data-sheet",
  "data-recovery",
  "data-protection",
] as const

export type IconName = typeof iconNames[number]
