// This file is generated by icon spritesheet generator

export const iconNames = [
  "debt",
  "database",
  "data_sheet",
  "data_recovery",
  "data_protection",
] as const

export type IconName = typeof iconNames[number]
